export const firstRenderData = {
  _result: {
    status: 'ok',
    reason: null,
  },
  courses: [
    {
      id: 24021,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        requests: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        attendance: true,
        leaderboard: true,
        lectureroom: false,
        attendance_admin: true,
        section_schedule: false,
      },
      enroll_begin_datetime: 1650277153006,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1650277153006,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 107449,
      title: 'df',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url: null,
      period: 4,
      version: 2,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: null,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 2,
      enrolled_student_count: 0,
      normal_lecture_count: 1,
      test_lecture_count: 0,
      normal_lecture_page_count: 1,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23925,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: false,
      is_post_student_email_enabled: false,
      is_post_tutor_email_enabled: false,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
        tab_menus_visibility: {
          boards: false,
          manage: true,
          configs: false,
          members: true,
          lectures: true,
          sections: true,
          tutoring: true,
          dashboard: true,
          libraries: true,
          leaderboard: true,
          lectureroom: false,
          section_schedule: false,
        },
      },
      enroll_begin_datetime: 1644202084016,
      enroll_end_datetime: null,
      release_datetime: 1649925479764,
      begin_datetime: 1644202084016,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: 12,
      enroll_type: 0,
      subscription_level: null,
      enroll_limit_number: null,
      price: '119000',
      price_usd: '99.17',
      discounted_price: '119000',
      discounted_price_usd: '99.17',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 106911,
      title: '자바스크립트 클론코딩',
      code: '',
      short_description:
        '인스타그램과 유튜브 웹사이트를 직접 내 손으로 한땀 한땀 따라 만들면서 자바스크립트와 리액트로 웹 프론트엔드를 개발해봅니다.',
      class_times: [],
      class_type: 0,
      taglist: ['웹', '클론코딩'],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/f1d93ffceadc4a1598898bd37c70325c/%E1%84%8C%E1%85%A1%E1%84%87%E1%85%A1%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%B8%E1%84%90%E1%85%B3%20%E1%84%8C%E1%85%AE%E1%86%BC%E1%84%80%E1%85%B3%E1%86%B8%402x.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=uy0m1T0Co3EoUEa0nme5n2kgnfClfGKJT/oPLT7CGP0%3D',
      period: 4,
      version: 25,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: false,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 3,
      last_review_status: 3,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 10,
      enrolled_student_count: 0,
      normal_lecture_count: 4,
      test_lecture_count: 0,
      normal_lecture_page_count: 33,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 5,
          tag_type: 1,
          name: 'korean',
        },
        {
          id: 3,
          tag_type: 0,
          name: 'intermediate',
        },
        {
          id: 14,
          tag_type: 3,
          name: 'webDeveloper',
        },
        {
          id: 19,
          tag_type: 2,
          name: 'javascript',
        },
      ],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23463,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: false,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        requests: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
      },
      enroll_begin_datetime: 1649150721278,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1649150721278,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 1,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 105634,
      title: 'ㅇㅇ',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url: null,
      period: 4,
      version: 0,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: null,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 1,
      enrolled_student_count: 0,
      normal_lecture_count: 0,
      test_lecture_count: 0,
      normal_lecture_page_count: 0,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23356,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        requests: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
        tab_menus_visibility: {
          boards: false,
          manage: true,
          configs: false,
          members: true,
          lectures: true,
          requests: true,
          sections: true,
          tutoring: true,
          dashboard: true,
          libraries: true,
          leaderboard: true,
          lectureroom: true,
          section_schedule: false,
        },
      },
      enroll_begin_datetime: 1648793421480,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1648793421480,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 105288,
      title: '테스트',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url: null,
      period: 4,
      version: 1,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: null,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 4,
      enrolled_student_count: 0,
      normal_lecture_count: 0,
      test_lecture_count: 0,
      normal_lecture_page_count: 0,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23355,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        requests: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: true,
        section_schedule: false,
        tab_menus_visibility: {
          boards: false,
          manage: true,
          configs: false,
          members: true,
          lectures: true,
          requests: true,
          sections: true,
          tutoring: true,
          dashboard: true,
          libraries: true,
          leaderboard: true,
          lectureroom: false,
          section_schedule: false,
        },
      },
      enroll_begin_datetime: 1648793331418,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1648793331418,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 3,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 105286,
      title: '라이브테스트',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url: null,
      period: 4,
      version: 2,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: null,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 2,
      enrolled_student_count: 0,
      normal_lecture_count: 0,
      test_lecture_count: 0,
      normal_lecture_page_count: 0,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23217,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {},
      enroll_begin_datetime: 1599020591286,
      enroll_end_datetime: 1640876400000,
      release_datetime: 1601949319538,
      begin_datetime: 1599020591286,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 0,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: false,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 104903,
      title: '프로그래밍  C++',
      code: '',
      short_description: 'C++로 게임 개발, 모바일 프로그램, 임베디드 프로그램 등 소프트웨어 전 분야에 활용해요!',
      class_times: [],
      class_type: 0,
      taglist: ['C++', 'cpp', '프로그래밍기초', '무료', '무료과목', '무료수강'],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/305cf1a710664d97a74dadd1ca2818ca/Group%20108%20%283%29.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=HIzjhlh/1/X/uazphy4CpnXEwBhKUVOVkDCGoWp2zAQ%3D',
      period: 4,
      version: 15,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: false,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 3,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 5,
      enrolled_student_count: 0,
      normal_lecture_count: 14,
      test_lecture_count: 0,
      normal_lecture_page_count: 135,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 2,
          tag_type: 0,
          name: 'beginner',
        },
        {
          id: 8,
          tag_type: 2,
          name: 'cpp',
        },
        {
          id: 12,
          tag_type: 3,
          name: 'programmer',
        },
      ],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23215,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {},
      enroll_begin_datetime: 1598836938069,
      enroll_end_datetime: 1640876400000,
      release_datetime: 1600837847313,
      begin_datetime: 1598836938069,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 0,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: false,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 104901,
      title: '프로그래밍 Java',
      code: '',
      short_description: 'Java로 시작하는 프로그래밍',
      class_times: [],
      class_type: 0,
      taglist: ['Java', '자바', '프로그래밍', '기초', '입문', '무료', '무료과목', '무료수강'],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/62bfb320fabb45559f6178ef76bff856/Group%20108%20%284%29.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=RjJz%2BgkUCh3LGuuFtQBGx%2B3VikPwpqN7Wok6EYI8f08%3D',
      period: 4,
      version: 19,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: false,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 3,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 1,
      enrolled_student_count: 0,
      normal_lecture_count: 5,
      test_lecture_count: 0,
      normal_lecture_page_count: 147,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 1,
          tag_type: 0,
          name: 'introduction',
        },
        {
          id: 9,
          tag_type: 2,
          name: 'java',
        },
        {
          id: 12,
          tag_type: 3,
          name: 'programmer',
        },
      ],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23214,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        helpcenter: true,
        leaderboard: true,
        lectureroom: false,
      },
      enroll_begin_datetime: 1619688873042,
      enroll_end_datetime: 1640876400000,
      release_datetime: 1623904753805,
      begin_datetime: 1619688873042,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 0,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 104900,
      title: '웹 프로그래밍 실무',
      code: '',
      short_description: '웹 프로그래밍 실무를 위한 기초 과목',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/e290a5d6fba944cc8a8d99bcd5b36254/%EC%BA%A1%EC%B2%98.PNG?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=ogfCV7F4MItrpiq%2B4NwHHXapBiotSZgXLZcrYyYX8n4%3D',
      period: 4,
      version: 23,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: false,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 3,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 3,
      enrolled_student_count: 0,
      normal_lecture_count: 4,
      test_lecture_count: 0,
      normal_lecture_page_count: 67,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23212,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {},
      enroll_begin_datetime: 1601871915240,
      enroll_end_datetime: 1640876400000,
      release_datetime: 1640590630735,
      begin_datetime: 1601871915240,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 0,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: false,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 104898,
      title: '정보처리수학',
      code: '',
      short_description: '고등학교 수학에서 다루는 개념들을 프로그램으로 구현해보는 과목!',
      class_times: [],
      class_type: 0,
      taglist: ['파이썬', '정보처리수학', '프로그래밍_기본개념', '무료', '무료과목', '무료수강'],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/11d3491bb3494e2ba3a53e95edae6446/Group%20108%20%281%29.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=XShczgdD%2B7167xXaQEW1zlBVuEeQAj7Td2sZTg0ZN1U%3D',
      period: 4,
      version: 31,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: false,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 3,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 1,
      enrolled_student_count: 0,
      normal_lecture_count: 6,
      test_lecture_count: 0,
      normal_lecture_page_count: 65,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 2,
          tag_type: 0,
          name: 'beginner',
        },
        {
          id: 10,
          tag_type: 2,
          name: 'python',
        },
        {
          id: 12,
          tag_type: 3,
          name: 'programmer',
        },
      ],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23211,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        live_streaming: true,
      },
      enroll_begin_datetime: 1597626743475,
      enroll_end_datetime: 1640876400000,
      release_datetime: 1598583456809,
      begin_datetime: 1597626743475,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 0,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: false,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 104897,
      title: '프로그래밍 PYTHON',
      code: '',
      short_description: '파이썬 기초를 차근차근 배워보세요!',
      class_times: [],
      class_type: 0,
      taglist: ['파이썬', 'python', '기초프로그래밍', '입문', '무료', '무료과목', '무료수강'],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/1412bbcdf8e74143bfc5a87f7b345786/Group%20108%20%286%29.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=jj4iFdMgtPs3TW8NkJwwYh2sjjq8kIivQqZxQDEhRcQ%3D',
      period: 4,
      version: 16,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: false,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 3,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 3,
      enrolled_student_count: 0,
      normal_lecture_count: 8,
      test_lecture_count: 0,
      normal_lecture_page_count: 118,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 1,
          tag_type: 0,
          name: 'introduction',
        },
        {
          id: 10,
          tag_type: 2,
          name: 'python',
        },
        {
          id: 12,
          tag_type: 3,
          name: 'programmer',
        },
      ],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 23149,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
      },
      enroll_begin_datetime: 1648547572140,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1648547572140,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 104587,
      title: '마크다운 에디터',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url: null,
      period: 4,
      version: 2,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: null,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 2,
      enrolled_student_count: 0,
      normal_lecture_count: 0,
      test_lecture_count: 0,
      normal_lecture_page_count: 0,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 5,
          tag_type: 1,
          name: 'korean',
        },
      ],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 22658,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
        tab_menus_visibility: {
          boards: false,
          manage: true,
          configs: false,
          members: true,
          lectures: true,
          sections: true,
          tutoring: true,
          dashboard: true,
          libraries: true,
          leaderboard: true,
          lectureroom: false,
          section_schedule: false,
        },
      },
      enroll_begin_datetime: 1632387283548,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1632387283548,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 103138,
      title: '알아두면 쓸데 있는 컴퓨터 사이언스',
      code: '',
      short_description: '프로그래밍 언어 학습 전 컴퓨터의 구조와 동작원리를 파악하고 IT 용어를 배워봅니다.',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/edd57077444f4a84bd9c6cb47a67a5d1/%EC%95%8C%EC%93%B8%EC%BB%B4%EC%82%AC%20%281%29.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=hG6RoGzPScyQ9NirvXRGf6JGw74E/IyADXobtGwk5s8%3D',
      period: 4,
      version: 11,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 4,
      enrolled_student_count: 1,
      normal_lecture_count: 4,
      test_lecture_count: 0,
      normal_lecture_page_count: 29,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 22458,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
      },
      enroll_begin_datetime: 1647570910274,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1647570910274,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: false,
        programming_language: true,
        total_video_duration: false,
        enrolled_student_count: false,
        auto_completion_condition: false,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 102693,
      title: '엘리스 프로모션',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url: null,
      period: 4,
      version: 7,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: null,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 4,
      enrolled_student_count: 0,
      normal_lecture_count: 1,
      test_lecture_count: 0,
      normal_lecture_page_count: 4,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 21951,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
      },
      enroll_begin_datetime: 1646991501258,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1646991501258,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 101218,
      title: '테스트',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url: null,
      period: 4,
      version: 1,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: null,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 3,
      enrolled_student_count: 0,
      normal_lecture_count: 0,
      test_lecture_count: 0,
      normal_lecture_page_count: 0,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 21892,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
      },
      enroll_begin_datetime: 1646961242506,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1646961242506,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: false,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 101079,
      title: '상세페이지TEST',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url: null,
      period: 4,
      version: 4,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: null,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 2,
      enrolled_student_count: 0,
      normal_lecture_count: 0,
      test_lecture_count: 0,
      normal_lecture_page_count: 0,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 21749,
      is_recommended: true,
      is_chat_room_disabled: false,
      is_post_student_info_visible: false,
      is_post_student_email_enabled: false,
      is_post_tutor_email_enabled: false,
      preference: {
        chatting: false,
        helpcenter: true,
        live_streaming: false,
        tab_menus_visibility: {
          boards: false,
          manage: true,
          configs: false,
          members: true,
          lectures: true,
          sections: true,
          tutoring: true,
          dashboard: true,
          libraries: true,
          leaderboard: true,
          lectureroom: false,
          section_schedule: false,
        },
      },
      enroll_begin_datetime: 1641002296000,
      enroll_end_datetime: null,
      release_datetime: 1646719404534,
      begin_datetime: 1641002296000,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: 12,
      enroll_type: 0,
      subscription_level: null,
      enroll_limit_number: null,
      price: '170000',
      price_usd: '141.67',
      discounted_price: '170000',
      discounted_price_usd: '141.67',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: {
        op: 'and',
        test_lecture_score: 200,
        normal_lecture_progress: 80,
      },
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: false,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 100698,
      title: '알고리즘을 위한 자료구조',
      code: '',
      short_description: '특정 프로그램 구현에 적합한 자료구조를 익히고, IT기업 기술 면접도 준비하는 과목!',
      class_times: [],
      class_type: 0,
      taglist: ['#기술면접', '자료구조', '컴퓨터과학', '스택', '큐', '트리'],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/d020684465334d09901cc79f79aa25a8/data-structure.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=UstmhmFtDR9hGY7HBLevaowWkvhZpdmoIovLNIiWa4Q%3D',
      period: 4,
      version: 7,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: false,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 3,
      last_review_status: 3,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 22,
      enrolled_student_count: 12,
      normal_lecture_count: 4,
      test_lecture_count: 1,
      normal_lecture_page_count: 46,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 4,
          tag_type: 0,
          name: 'advanced',
        },
        {
          id: 10,
          tag_type: 2,
          name: 'python',
        },
        {
          id: 23,
          tag_type: 3,
          name: 'algorithm',
        },
      ],
      tracks: [
        {
          id: 1869,
          title: '알고리즘 코딩테스트 완벽 대비반',
        },
      ],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 21468,
      is_recommended: true,
      is_chat_room_disabled: false,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        live_streaming: true,
        supplement_column_width: 0.25,
        click_to_play_supplement_gif: true,
        render_markdown_in_quiz_options: true,
      },
      enroll_begin_datetime: 1640995943000,
      enroll_end_datetime: null,
      release_datetime: 1646189654665,
      begin_datetime: 1640995943000,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 0,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: true,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: false,
        enrolled_student_count: false,
        auto_completion_condition: false,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 101128,
      title: '프로그래밍 PYTHON',
      code: '',
      short_description: '파이썬 기초를 차근차근 배워보세요!',
      class_times: [],
      class_type: 0,
      taglist: ['파이썬', 'python', '기초프로그래밍', '입문', '무료', '무료과목', '무료수강'],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/1412bbcdf8e74143bfc5a87f7b345786/Group%20108%20%286%29.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=jj4iFdMgtPs3TW8NkJwwYh2sjjq8kIivQqZxQDEhRcQ%3D',
      period: 4,
      version: 24,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 3,
      last_review_status: 3,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 366,
      enrolled_student_count: 357,
      normal_lecture_count: 8,
      test_lecture_count: 0,
      normal_lecture_page_count: 118,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 1,
          tag_type: 0,
          name: 'introduction',
        },
        {
          id: 10,
          tag_type: 2,
          name: 'python',
        },
        {
          id: 12,
          tag_type: 3,
          name: 'programmer',
        },
      ],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 21401,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: false,
      is_post_student_email_enabled: false,
      is_post_tutor_email_enabled: false,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
        tab_menus_visibility: {
          boards: false,
          manage: true,
          configs: false,
          members: true,
          lectures: true,
          sections: true,
          tutoring: true,
          dashboard: true,
          libraries: true,
          leaderboard: true,
          lectureroom: false,
          section_schedule: false,
        },
      },
      enroll_begin_datetime: 1639991960337,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1639991960337,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 99593,
      title: 'CNN과 RNN 이해하기',
      code: '',
      short_description: '인공 신경망의 쌍두마차를 이해하는 과목입니다.',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/18a10188dd524742ac4705a1e02737fb/cnn%2Crnn.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=ritm64PgPAmemfGdOP2oUyXaySgChq9klaKTieeqYrc%3D',
      period: 4,
      version: 7,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 5,
      enrolled_student_count: 1,
      normal_lecture_count: 4,
      test_lecture_count: 0,
      normal_lecture_page_count: 57,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 21400,
      is_recommended: false,
      is_chat_room_disabled: true,
      is_post_student_info_visible: true,
      is_post_student_email_enabled: true,
      is_post_tutor_email_enabled: true,
      preference: {
        boards: false,
        manage: true,
        configs: false,
        members: true,
        lectures: true,
        sections: true,
        tutoring: true,
        dashboard: true,
        libraries: true,
        leaderboard: true,
        lectureroom: false,
        section_schedule: false,
      },
      enroll_begin_datetime: 1633500511892,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1633500511892,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 5,
      subscription_level: null,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: null,
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: true,
        programming_language: true,
        total_video_duration: true,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 99592,
      title: '머신러닝을 위한 수학',
      code: '',
      short_description: '',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/811a5f8b427b4ad0ab619592e5bee9b0/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EC%9D%84%20%EC%9C%84%ED%95%9C%20%EC%88%98%ED%95%99.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=HPEHUFLKVbGZf2eFzTW92G7J6AJFFX77yo8M5LU7t44%3D',
      period: 4,
      version: 1,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: true,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 2,
      enrolled_student_count: 0,
      normal_lecture_count: 4,
      test_lecture_count: 1,
      normal_lecture_page_count: 42,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
    {
      id: 21399,
      is_recommended: true,
      is_chat_room_disabled: true,
      is_post_student_info_visible: false,
      is_post_student_email_enabled: false,
      is_post_tutor_email_enabled: false,
      preference: {
        live_streaming: true,
      },
      enroll_begin_datetime: 1577064944085,
      enroll_end_datetime: null,
      release_datetime: null,
      begin_datetime: 1579484144085,
      end_datetime: null,
      complete_datetime: null,
      enrolled_role_period: null,
      enroll_type: 4,
      subscription_level: 10,
      enroll_limit_number: null,
      price: '0',
      price_usd: '0.00',
      discounted_price: '0',
      discounted_price_usd: '0.00',
      discount_begin_datetime: null,
      discount_end_datetime: null,
      discount_title: null,
      discount_rate: null,
      auto_completion_condition: {
        normal_lecture_progress: 80,
      },
      course_type: 0,
      info_summary_visibility_dict: {
        level: true,
        period: false,
        class_type: true,
        class_times: false,
        exercise_page_count: false,
        programming_language: true,
        total_video_duration: false,
        enrolled_student_count: true,
        auto_completion_condition: true,
        lecture_page_access_period: true,
      },
      is_exercise_deprecated: false,
      last_course_info_id: 99591,
      title: '2022 TensorFlow 2.0 튜토리얼',
      code: '',
      short_description: '텐서플로우 튜토리얼 실습을 엘리스 플랫폼에서 학습합니다.',
      class_times: [],
      class_type: 0,
      taglist: [],
      promote_video_url: null,
      logo_file_url:
        'https://cdn-api.elice.io/api/file/9c173facce6240ed9c0bd0b3c309981e/tensorflow.png?se=2022-05-12T00%3A15%3A00Z&sp=rt&sv=2020-10-02&sr=b&sig=Pn/959%2BFLGU%2BMjU0P9vMrVRZ7x0FVm3Q5vgINkEcEcY%3D',
      period: 4,
      version: 144,
      is_discounted: false,
      attendance_info: {
        is_enabled: false,
        active_end_date: '0001-01-01',
        active_begin_date: '0001-01-01',
        check_in_end_time: '24:00',
        check_out_end_time: '24:00',
        check_in_begin_time: '00:00',
        check_out_begin_time: '00:00',
        required_stay_seconds: 0,
      },
      last_attendance_updated_date: null,
      is_free: false,
      library_access_type: null,
      library_type: 1,
      is_enroll_noti_enabled: false,
      is_datetime_enrollable: true,
      agreement_info: {
        title: '',
        is_enabled: false,
        description: '',
      },
      status: 0,
      last_review_status: 0,
      course_agreed_datetime: null,
      course_role: 0,
      has_past_course_role: false,
      enrolled_user_count: 2,
      enrolled_student_count: 0,
      normal_lecture_count: 9,
      test_lecture_count: 0,
      normal_lecture_page_count: 43,
      enrolled_role_begin_datetime: null,
      enrolled_role_end_datetime: null,
      lecture_page_read_info: null,
      tags: [
        {
          id: 4,
          tag_type: 0,
          name: 'advanced',
        },
        {
          id: 10,
          tag_type: 2,
          name: 'python',
        },
        {
          id: 22,
          tag_type: 3,
          name: 'aiml',
        },
      ],
      tracks: [],
      instructors: [],
      test_lecture: null,
    },
  ],
  course_count: 170,
};
